### ISSUE TITLE
Add comment on README about Apple M1 with older iOS

### ISSUE THREAD

**Issue by MattiaPugliatti** [MattiaPugliatti/corto#19]
Please, send me a sentence

**Comment by MattiaPugliatti** [comment]
Mattia to send stuff from his previous installation (Hardware and IOS)

**Comment by MattiaPugliatti** [comment]
Add comments on Apple/Windows and/or Linux

**Comment by micmaestrini** [comment]
fix with commit [f05986c](https://github.com/MattiaPugliatti/corto/commit/f05986c111e1f6719434c5b4378fd6e08385d64b)

**Comment by micmaestrini** [comment]
fix with commit [f05986c](https://github.com/MattiaPugliatti/corto/commit/f05986c111e1f6719434c5b4378fd6e08385d64b)
